image:https://travis-ci.org/oasp/oasp-docgen.svg?branch=master["Build Status",link="https://travis-ci.org/oasp/oasp-docgen"]

= oasp-docgen

Documentation generator that can generate a complete and self-contained documentation as PDF, ePub and HTML from Asciidoc Wiki pages.

[NOTE]
===============================
*OASP has been superseded by devonfw*, the Open Source Standard Software Development Platform for state of the art Cloud Native Micro Service and Multi Platform Rich Web Apps, supported by Capgemini.

See http://devonfw.com and on Github http://github.com/devonfw

Individual products within OASP have been renamed to a corresponding one in devonfw. 

For example:

- OAPS4j -> devon4j
- OASP4js -> devon4ng
- OASP4NET -> devon4NET

devonfw® is an exclusive and registered (European Trademark) product of Capgemini. Capgemini reserves all intellectual and industrial property rights over devonfw but publishes it under the Apache License, Version 2 – like OASP-  which makes devonfw 100% Open Source.
See: https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)
===============================

== Usage

1. Create a pom.xml in your wiki project inheriting the latest oasp-docgen pom
2. Indicate the initial asciidoc document to start generation from by the `oasp.wiki.page` property:
+
```xml
<properties>
  <oasp.wiki.page>CobiGen</oasp.wiki.page>
</properties>
```
3. Run mvn site on your wiki project to generate the PDF to be found in `/target/generated-docs`

Experimental:

Develop your own PDF style by using the asciidoctor facilities. You can point the generation to your new theme by stating the `oasp.asciidoc.pdf.stylesdir` property:

```xml
<properties>
  <oasp.asciidoc.pdf.stylesdir>./theme</oasp.asciidoc.pdf.stylesdir>
</properties>
```
